name: main

on:
  push:
    paths-ignore:
      - '.github/workflows/test-*'
      - 'test/alpine/**'
      - 'test/debian/**'
      - 'test/fedora/**'
      - 'README.md'
  pull_request:
  workflow_dispatch:
    
jobs:
  build:
    name: Build

    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4.1.6

      -
        name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.22.3'
      
      - 
        name: Check Go format
        run: |
          gofmtout=$(gofmt -l .); [ -z "${gofmtout}" ] || { echo "Detected malformatted go files. Run 'go fmt ./..." >&2; echo $gofmtout; exit 1; }
      
      -
        name: Get dependencies
        run: |
          go mod download

      - 
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.1
        with:
          terraform_version: "1.6.3"

      - 
        name: Verify generated files
        run: |
          go generate ./...;
          git diff --compact-summary --exit-code || (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)

      -
        name: Build
        run: |
          go build -v .
      
      -
        name: Run unit tests
        run: |
          go test -v ./...

  release:
    needs: build
    name: Release
    
    # only on push events and if commit has version tag
    if: ${{ github.repository == 'stevenbuglione/terraform-provider-system' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}

    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4.1.6

      -
        name: Unshallow
        run: git fetch --prune --unshallow

      -
        name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: '1.22.3'

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.9.1
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
